// Copyright 2026 Timofey Krestyanov
// SPDX-License-Identifier: Apache-2.0
package com.timkrest.framehud.internal

import com.timkrest.framehud.BaselineComparison
import com.timkrest.framehud.FramePhase
import com.timkrest.framehud.Incident
import com.timkrest.framehud.IncidentWindow
import com.timkrest.framehud.IntervalComparison
import com.timkrest.framehud.IntervalStats
import com.timkrest.framehud.MainThreadBlock
import com.timkrest.framehud.MetricDelta
import com.timkrest.framehud.PhaseAverages
import java.util.Locale

internal fun SessionSnapshot.toHtml(): String = buildString {
    append("<!doctype html>\n<html lang=\"en\">\n<head>\n")
    append("<meta charset=\"utf-8\">\n")
    append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    append("<title>FrameHUD · ").append(escapeHtml(packageName)).append("</title>\n")
    append("<style>").append(REPORT_CSS).append("</style>\n</head>\n<body>\n")
    append(reportBody())
    append("</body>\n</html>\n")
}

private fun SessionSnapshot.reportBody(): String = buildHtmlBody {
    header(title = "FrameHUD session", meta = subtitle())
    tiles {
        tile(session.frames.toString(), "frames")
        tile(formatMs(session.p95FrameMs), "p95")
        tile(formatPercent(session.jankPercent), "jank")
        tile(session.frozenFrames.toString(), "frozen")
    }
    confidence(this@reportBody)
    measurement(this@reportBody)
    stats(this@reportBody)
    screens(this@reportBody)
    phases(this@reportBody)
    baseline(this@reportBody)
    frameWindow(this@reportBody)
    worstFrames(this@reportBody)
    incidents(this@reportBody)
    counters(this@reportBody)
    environment(this@reportBody)
    footer("Generated by FrameHUD $frameHudVersion. Measurements never leave the device.")
}

private fun SessionSnapshot.subtitle(): String = buildString {
    append(packageName)
    appVersionName?.let { append(' ').append(it) }
    append(" (").append(appVersionCode).append(")")
    append(" · ").append(environment.label)
    append(" · ").append(formatTimestamp(takenAtEpochMs))
}

private fun HtmlScope.confidence(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement confidence") {
        val sessionIssues = session.confidence.issues
        val screenOnlyIssues = screen.confidence.issues - sessionIssues.toSet()
        if (sessionIssues.isEmpty() && screenOnlyIssues.isEmpty()) {
            meta("No issues.")
            return@section
        }
        list {
            for (issue in sessionIssues) item(issue.summary)
            for (issue in screenOnlyIssues) item("${issue.summary} — this screen only")
        }
    }
}

private fun HtmlScope.measurement(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement") {
        table {
            row("State", measurementState())
            row("Screen", screenName ?: "—")
            row("Mark", mark ?: "—")
            if (context.isNotEmpty()) {
                chipRow("Context", context.map { (key, value) -> "$key=$value" })
            }
            row("Display", "${formatFloat(display.refreshRateHz)} Hz, budget ${formatMs(display.frameBudgetMs)}")
            flightRecording?.let { row("Perfetto trigger", it.summary()) }
        }
    }
}

private fun FlightRecording.summary(): String = when (timesAsked) {
    0 -> "$trigger, never asked to retain the trace"
    1 -> "$trigger, asked to retain the trace once"
    else -> "$trigger, asked to retain the trace $timesAsked times"
}

private fun SessionSnapshot.measurementState(): String = when {
    !isEnabled -> "disabled"
    isFrozen -> "collecting, readings frozen"
    else -> "collecting"
}

private fun HtmlScope.stats(snapshot: SessionSnapshot) = with(snapshot) {
    section("Stats") {
        table {
            headings("", "Session", "Screen")
            statRow(snapshot, "Frames") { it.frames.toString() }
            statRow(snapshot, "Duration") { formatSeconds(it.durationMs) }
            statRow(snapshot, "p50") { formatMs(it.p50FrameMs) }
            statRow(snapshot, "p95") { formatMs(it.p95FrameMs) }
            statRow(snapshot, "p99") { formatMs(it.p99FrameMs) }
            statRow(snapshot, "Jank") { formatPercent(it.jankPercent) }
            statRow(snapshot, "Lost time") { formatMs(it.lostTimeMs) }
            statRow(snapshot, "Frozen frames") { it.frozenFrames.toString() }
            statRow(snapshot, "Longest jank streak") { it.maxJankStreak.toString() }
            statRow(snapshot, "Dropped reports") { it.droppedReports.toString() }
        }
        if (session.droppedReports > 0) {
            caution("Dropped reports above zero: every other figure is undersampled.")
        }
    }
}

private fun TableScope.statRow(snapshot: SessionSnapshot, label: String, format: (IntervalStats) -> String) = with(snapshot) {
    row(label, format(session), format(screen))
}

private fun HtmlScope.screens(snapshot: SessionSnapshot) = with(snapshot) {
    val ranked = intervals.worstScreensFirst()
    if (ranked.isEmpty()) return@with
    section("Screens") {
        meta("Worst first: frozen frames, then jank, then p95. Too few frames to judge and it goes last.")
        table {
            headings("", "Frames", "Jank", "p95", "Frozen", "Budget")
            for (screen in ranked) {
                row(
                    screen.id.name,
                    screen.stats.frames.toString(),
                    formatPercent(screen.stats.jankPercent),
                    formatMs(screen.stats.p95FrameMs),
                    screen.stats.frozenFrames.toString(),
                    formatMs(screen.frameBudgetMs),
                )
            }
        }
    }
}

private fun HtmlScope.phases(snapshot: SessionSnapshot) = with(snapshot) {
    section("Where the time went") {
        meta("Session ${session.phases.boundBy()}, screen ${screen.phases.boundBy()}.")
        table {
            headings("", "Session", "Screen", "Peak since reset")
            phaseRow(snapshot, FramePhase.UNKNOWN_DELAY.label(), phases.unknownDelay.peak) { it.unknownDelay }
            phaseRow(snapshot, FramePhase.INPUT.label(), phases.input.peak) { it.input }
            phaseRow(snapshot, FramePhase.ANIMATION.label(), phases.animation.peak) { it.animation }
            phaseRow(snapshot, FramePhase.LAYOUT.label(), phases.layout.peak) { it.layout }
            phaseRow(snapshot, FramePhase.DRAW.label(), phases.draw.peak) { it.draw }
            phaseRow(snapshot, "UI thread", peakMs = null) { it.cpu }
            phaseRow(snapshot, FramePhase.SYNC.label(), phases.sync.peak) { it.sync }
            phaseRow(snapshot, FramePhase.COMMAND_ISSUE.label(), phases.commandIssue.peak) { it.commandIssue }
            phaseRow(snapshot, FramePhase.SWAP_BUFFERS.label(), phases.swapBuffers.peak) { it.swapBuffers }
            phaseRow(snapshot, "Render thread", peakMs = null) { it.render }
            if (session.phases.gpu != null) phaseRow(snapshot, FramePhase.GPU.label(), phases.gpu?.peak) { it.gpu }
            phaseRow(snapshot, "Unattributed", peakMs = null) { it.unattributed }
            phaseRow(snapshot, FramePhase.TOTAL.label(), phases.total.peak) { it.total }
        }
    }
}

private fun TableScope.phaseRow(
    snapshot: SessionSnapshot,
    label: String,
    peakMs: Float?,
    select: (PhaseAverages) -> Float?,
) = with(snapshot) {
    row(label, formatMs(select(session.phases)), formatMs(select(screen.phases)), formatMs(peakMs))
}

private fun HtmlScope.baseline(snapshot: SessionSnapshot) {
    val comparison = snapshot.baseline
    if (comparison is BaselineComparison.NoBaseline) return
    section("Baseline") {
        when (comparison) {
            BaselineComparison.NoBaseline -> Unit
            is BaselineComparison.OtherEnvironment -> caution(
                "Recorded on ${comparison.recorded.label}, this run is ${comparison.current.label}. " +
                    "Nothing here compares across the two.",
            )
            is BaselineComparison.Compared -> {
                if (comparison.intervals.isEmpty()) {
                    meta("Nothing this run measured has a baseline yet.")
                } else {
                    for (interval in comparison.intervals) intervalComparison(interval)
                }
            }
        }
    }
}

private fun HtmlScope.intervalComparison(comparison: IntervalComparison) {
    meta(
        "${comparison.id.label} · baseline of ${comparison.recordedRuns} run(s) · " +
            "${comparison.currentFrames} frames this run",
    )
    if (comparison.metrics.isNotEmpty()) {
        table {
            headings("", "Baseline", "Runs", "This run", "Change")
            for (delta in comparison.metrics) {
                row(
                    delta.metric.label(),
                    delta.metric.format(delta.baseline),
                    delta.baselineRuns.toString(),
                    delta.metric.format(delta.current),
                    formatChange(delta),
                )
            }
        }
    }
    if (comparison.uncompared.isNotEmpty()) {
        meta("Not compared: ${comparison.uncompared.joinToString { it.summary }}.")
    }
    val grown = comparison.grownPhases.firstOrNull() ?: return
    meta("${grown.grewTheMost()}.")
}

private fun formatChange(delta: MetricDelta): String {
    val change = delta.metric.format(delta.change).let { if (delta.change > 0f) "+$it" else it }
    val percent = delta.changePercent?.let { " ${formatChangePercent(it)}" }.orEmpty()
    return change + percent
}

private fun PhaseAverages.boundBy(): String =
    "${bottleneckStage.name.lowercase(Locale.US)} bound at ${formatMs(bottleneck)} per frame"

private fun HtmlScope.frameWindow(snapshot: SessionSnapshot) = with(snapshot) {
    section("Frame window") {
        if (window.frames.size == 0) {
            meta("No frames in the window.")
            return@section
        }
        meta(
            "Last ${window.frames.size} frames: p95 ${formatMs(window.p95FrameMs)} · " +
                "worst ${formatMs(window.worstFrameMs)} · red bars ran past their budget. " +
                "${window.fps} frames in the last second.",
        )
        markup(frameChart(history = window.frames, label = "Recent frame durations"))
    }
}

private fun HtmlScope.incidents(snapshot: SessionSnapshot) = with(snapshot) {
    if (incidents.isEmpty()) return@with
    section("Incidents") {
        for (incident in incidents) {
            meta(incidentHeading(incident))
            meta(incidentDetails(incident.worst))
            markup(
                frameChart(
                    history = incident.worst.frames,
                    label = "Frames around the incident",
                    framesBeforeTrigger = incident.worst.framesBeforeTrigger,
                ),
            )
            mainThreadBlock(incident.worst.mainThreadBlock)
        }
    }
}

private fun SessionSnapshot.incidentHeading(incident: Incident): String = buildString {
    append(incident.worst.trigger.summary)
    if (incident.occurrences == 1) {
        append(" · at ").append(formatTimeOfDay(incident.firstAtEpochMs))
        return@buildString
    }
    append(" · ").append(incident.occurrences).append(" times between ")
    append(formatTimeOfDay(incident.firstAtEpochMs)).append(" and ").append(formatTimeOfDay(incident.lastAtEpochMs))
    append(", worst at ").append(formatTimeOfDay(incident.worst.triggeredAtEpochMs))
}

private fun incidentDetails(worst: IncidentWindow): String {
    val stats = worst.stats
    return listOfNotNull(
        "${stats.frames} frames, ${worst.framesBeforeTrigger} before the trigger",
        "jank ${formatPercent(stats.jankPercent)}",
        "p95 ${formatMs(stats.p95FrameMs)}",
        "frozen ${stats.frozenFrames}".takeIf { stats.frozenFrames > 0 },
        "dropped reports ${stats.droppedReports}".takeIf { stats.droppedReports > 0 },
        "heap ${worst.memory.usedHeapMb} MB",
        worst.process.cpuPercent?.let { "cpu ${formatPercent(it)}" },
        worst.process.pssMb?.let { "pss $it MB" },
        worst.thermal.level.takeIf { it.isThrottling }?.let { "thermal ${it.name.lowercase(Locale.US)}" },
    ).plus(worst.counters.map { "${it.name} ${it.value}" }).joinToString(INCIDENT_DETAIL_SEPARATOR)
}

private fun HtmlScope.mainThreadBlock(block: MainThreadBlock) {
    if (block.calls.isEmpty()) return
    meta("Main thread blocked ${block.durationMs} ms, ${block.stacksTaken} stacks taken")
    list {
        for (call in block.calls) item("${call.samples}x ${call.name}")
    }
}

private fun HtmlScope.worstFrames(snapshot: SessionSnapshot) = with(snapshot) {
    if (worstFrames.isEmpty()) return@with
    section("Worst frames") {
        table {
            headings("Time", "Duration")
            for (frame in worstFrames) {
                cells(formatTimeOfDay(frameEndEpochMs(frame.endNs)), formatMs(frame.totalMs))
            }
        }
    }
}

private fun HtmlScope.counters(snapshot: SessionSnapshot) = with(snapshot) {
    if (counters.isEmpty()) return@with
    section("Counters") {
        table {
            for (counter in counters) {
                val peak = counter.peakSinceReset.takeIf { it > counter.value }
                row(counter.name, peaked("${counter.value}", peak?.toString()))
            }
        }
    }
}

private fun HtmlScope.environment(snapshot: SessionSnapshot) = with(snapshot) {
    section("Environment") {
        table {
            row("Heap", "${memory.usedHeapMb} of ${memory.maxHeapMb} MB, peak ${memory.peakUsedHeapMb} MB")
            row("Native heap", "${memory.nativeHeapMb} MB, peak ${memory.peakNativeHeapMb} MB")
            row("GC since reset", "${memory.gcCount} runs, ${memory.gcTimeMs} ms")
            val headroom = thermal.headroom?.let { ", headroom ${formatFloat(it)}" }.orEmpty()
            row("Thermal", thermal.level.name.lowercase(Locale.US) + headroom)
            process.cpuPercent?.let { row("Process CPU", peaked(formatPercent(it), formatPercent(process.peakCpuPercent))) }
            process.pssMb?.let { row("PSS", peaked("$it MB", process.peakPssMb?.let { peak -> "$peak MB" })) }
            process.threads?.let { row("Threads", peaked("$it", process.peakThreads?.toString())) }
            process.openFiles?.let { row("Open files", peaked("$it", process.peakOpenFiles?.toString())) }
        }
        if (thermal.level.isThrottling) {
            caution("Thermal throttling: timings are not comparable to a cold run.")
        }
    }
}

private const val INCIDENT_DETAIL_SEPARATOR = " · "
