package com.timkrest.framehud.internal

import com.timkrest.framehud.FrameHistory
import com.timkrest.framehud.PhaseAverages
import com.timkrest.framehud.PipelineStage
import com.timkrest.framehud.SessionStats
import java.util.Locale
import kotlin.math.max

internal fun SessionSnapshot.toHtml(): String = buildString {
    append("<!doctype html>\n<html lang=\"en\">\n<head>\n")
    append("<meta charset=\"utf-8\">\n")
    append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    append("<title>FrameHUD · ").append(escapeHtml(packageName)).append("</title>\n")
    append("<style>").append(REPORT_CSS).append("</style>\n</head>\n<body>\n")
    append(reportBody())
    append("</body>\n</html>\n")
}

private fun SessionSnapshot.reportBody(): String = buildHtmlBody {
    header(title = "FrameHUD session", meta = subtitle())
    tiles {
        tile(formatCount(session.frames), "frames")
        tile(formatMs(session.p95FrameMs), "p95")
        tile(formatPercent(session.jankPercent), "jank")
        tile(formatCount(session.frozenFrames), "frozen")
    }
    confidence(this@reportBody)
    measurement(this@reportBody)
    stats(this@reportBody)
    phases(this@reportBody)
    frameWindow(this@reportBody)
    worstFrames(this@reportBody)
    environment(this@reportBody)
    footer("Generated by FrameHUD $frameHudVersion. Measurements never leave the device.")
}

private fun SessionSnapshot.subtitle(): String = buildString {
    append(packageName)
    appVersionName?.let { append(' ').append(it) }
    append(" (").append(appVersionCode).append(")")
    append(" · ").append(manufacturer).append(' ').append(model)
    append(", API ").append(apiLevel)
    append(" · ").append(formatTimestamp(takenAtEpochMs))
}

private fun HtmlScope.confidence(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement confidence") {
        val sessionIssues = session.confidence.issues
        val screenOnlyIssues = screen.confidence.issues - sessionIssues.toSet()
        if (sessionIssues.isEmpty() && screenOnlyIssues.isEmpty()) {
            meta("No issues.")
            return@section
        }
        list {
            for (issue in sessionIssues) item(issue.summary)
            for (issue in screenOnlyIssues) item("${issue.summary} — this screen only")
        }
    }
}

private fun HtmlScope.measurement(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement") {
        table {
            row("State", measurementState())
            row("Screen", screenName ?: "—")
            row("Mark", mark ?: "—")
            if (context.isNotEmpty()) {
                chipRow("Context", context.map { (key, value) -> "$key=$value" })
            }
            row("Display", "${formatFloat(display.refreshRateHz)} Hz, budget ${formatMs(display.frameBudgetMs)}")
        }
    }
}

private fun SessionSnapshot.measurementState(): String = when {
    !isEnabled -> "disabled"
    isFrozen -> "collecting, readings frozen"
    else -> "collecting"
}

private fun HtmlScope.stats(snapshot: SessionSnapshot) = with(snapshot) {
    section("Stats") {
        table {
            headings("", "Session", "Screen")
            statRow(snapshot, "Frames") { formatCount(it.frames) }
            statRow(snapshot, "Duration") { formatSeconds(it.durationMs) }
            statRow(snapshot, "p50") { formatMs(it.p50FrameMs) }
            statRow(snapshot, "p95") { formatMs(it.p95FrameMs) }
            statRow(snapshot, "p99") { formatMs(it.p99FrameMs) }
            statRow(snapshot, "Jank") { formatPercent(it.jankPercent) }
            statRow(snapshot, "Lost time") { formatMs(it.lostTimeMs) }
            statRow(snapshot, "Frozen frames") { formatCount(it.frozenFrames) }
            statRow(snapshot, "Longest jank streak") { formatCount(it.maxJankStreak) }
            statRow(snapshot, "Dropped reports") { formatCount(it.droppedReports) }
        }
        if (session.droppedReports > 0) {
            caution("Dropped reports above zero: every other figure is undersampled.")
        }
    }
}

private fun TableScope.statRow(snapshot: SessionSnapshot, label: String, format: (SessionStats) -> String) = with(snapshot) {
    row(label, format(session), format(screen))
}

private fun HtmlScope.phases(snapshot: SessionSnapshot) = with(snapshot) {
    section("Where the time went") {
        meta("Session ${session.phases.boundBy()}, screen ${screen.phases.boundBy()}.")
        table {
            headings("", "Session", "Screen", "Peak since reset")
            phaseRow(snapshot, "Delay before start", phases.unknownDelay.peak) { it.unknownDelay }
            phaseRow(snapshot, "Input", phases.input.peak) { it.input }
            phaseRow(snapshot, "Animation", phases.animation.peak) { it.animation }
            phaseRow(snapshot, "Layout", phases.layout.peak) { it.layout }
            phaseRow(snapshot, "Draw", phases.draw.peak) { it.draw }
            phaseRow(snapshot, "UI thread", peakMs = null) { it.cpu }
            phaseRow(snapshot, "Sync", phases.sync.peak) { it.sync }
            phaseRow(snapshot, "Command issue", phases.commandIssue.peak) { it.commandIssue }
            phaseRow(snapshot, "Swap buffers", phases.swapBuffers.peak) { it.swapBuffers }
            phaseRow(snapshot, "Render thread", peakMs = null) { it.render }
            if (session.phases.isGpuAvailable) phaseRow(snapshot, "GPU", phases.gpu.peak) { it.gpu }
            phaseRow(snapshot, "Unattributed", peakMs = null) { it.other }
            phaseRow(snapshot, "Total", phases.total.peak) { it.total }
        }
    }
}

private fun TableScope.phaseRow(
    snapshot: SessionSnapshot,
    label: String,
    peakMs: Float?,
    select: (PhaseAverages) -> Float,
) = with(snapshot) {
    row(label, formatMs(select(session.phases)), formatMs(select(screen.phases)), peakMs?.let(::formatMs) ?: "—")
}

private fun PhaseAverages.boundBy(): String {
    val averageMs = when (bottleneckStage) {
        PipelineStage.CPU -> cpu
        PipelineStage.RENDER -> render
        PipelineStage.GPU -> gpu
    }
    return "${bottleneckStage.name.lowercase(Locale.US)} bound at ${formatMs(averageMs)} per frame"
}

private fun HtmlScope.frameWindow(snapshot: SessionSnapshot) = with(snapshot) {
    section("Frame window") {
        if (window.history.size == 0) {
            meta("No frames in the window.")
            return@section
        }
        meta(
            "Last ${window.history.size} frames: p95 ${formatMs(window.p95FrameMs)} · " +
                "worst ${formatMs(window.worstFrameMs)} · red bars ran past their deadline. " +
                "${window.fps} frames in the last second.",
        )
        markup(frameChart(window.history))
    }
}

private fun frameChart(history: FrameHistory): String {
    var scaleMs = 0f
    for (index in 0 until history.size) {
        scaleMs = max(scaleMs, max(history.totalMsAt(index), history.deadlineMsAt(index)))
    }
    if (scaleMs <= 0f) return ""
    scaleMs *= CHART_HEADROOM

    return buildString {
        append("<svg viewBox=\"0 0 $CHART_WIDTH $CHART_HEIGHT\" preserveAspectRatio=\"none\" role=\"img\" ")
        append("aria-label=\"Recent frame durations\">\n")
        val step = CHART_WIDTH / history.size
        val barWidth = step * CHART_BAR_SHARE
        for (index in 0 until history.size) {
            val totalMs = history.totalMsAt(index)
            val deadlineMs = history.deadlineMsAt(index)
            val height = CHART_HEIGHT * (totalMs / scaleMs)
            val cssClass = if (totalMs > deadlineMs) "janky" else "ok"
            append("<rect class=\"").append(cssClass).append("\" x=\"").append(formatFloat(step * index))
            append("\" y=\"").append(formatFloat(CHART_HEIGHT - height))
            append("\" width=\"").append(formatFloat(barWidth))
            append("\" height=\"").append(formatFloat(height)).append("\"/>\n")

            val deadlineY = CHART_HEIGHT * (1f - deadlineMs / scaleMs)
            append("<line class=\"deadline\" x1=\"").append(formatFloat(step * index))
            append("\" x2=\"").append(formatFloat(step * index + barWidth))
            append("\" y1=\"").append(formatFloat(deadlineY))
            append("\" y2=\"").append(formatFloat(deadlineY)).append("\"/>\n")
        }
        append("</svg>\n")
    }
}

private fun HtmlScope.worstFrames(snapshot: SessionSnapshot) = with(snapshot) {
    if (worstFrames.isEmpty()) return
    section("Worst frames") {
        table {
            headings("Time", "Duration")
            for (frame in worstFrames) {
                cells(formatTimeOfDay(frameEndEpochMs(frame.endNs)), formatMs(frame.totalMs))
            }
        }
    }
}

private fun HtmlScope.environment(snapshot: SessionSnapshot) = with(snapshot) {
    section("Environment") {
        table {
            row("Heap", "${memory.usedHeapMb} of ${memory.maxHeapMb} MB, peak ${memory.peakUsedHeapMb} MB")
            row("Native heap", "${memory.nativeHeapMb} MB, peak ${memory.peakNativeHeapMb} MB")
            row("GC since reset", "${memory.gcCount} runs, ${memory.gcTimeMs} ms")
            val headroom = thermal.headroom?.let { ", headroom ${formatFloat(it)}" }.orEmpty()
            row("Thermal", thermal.level.name.lowercase(Locale.US) + headroom)
        }
        if (thermal.level.isThrottling) {
            caution("Thermal throttling: timings are not comparable to a cold run.")
        }
    }
}

private fun formatMs(value: Float): String = "${formatFloat(value)} ms"

private fun formatPercent(value: Float): String = "${formatFloat(value)}%"

private fun formatSeconds(durationMs: Long): String = String.format(Locale.US, "%.1f s", durationMs / MS_PER_SECOND_D)

private fun formatCount(value: Int): String = value.toString()

private fun formatFloat(value: Float): String = String.format(Locale.US, "%.1f", value)

private const val MS_PER_SECOND_D = 1000.0
private const val CHART_WIDTH = 600f
private const val CHART_HEIGHT = 120f
private const val CHART_BAR_SHARE = 0.8f
private const val CHART_HEADROOM = 1.05f

private val REPORT_CSS = """
    :root { color-scheme: light dark;
      --bg: #f7f7f5; --card: #ffffff; --text: #1c1c1a; --muted: #6d6d68; --line: #e4e4df;
      --ok: #4c9a52; --janky: #c94f42; --deadline: #1c1c1a; --caution: #9a6b00; }
    @media (prefers-color-scheme: dark) { :root {
      --bg: #191918; --card: #212120; --text: #ececea; --muted: #9c9c96; --line: #33332f;
      --ok: #5aa860; --janky: #d8695c; --deadline: #ececea; --caution: #d0a13e; } }
    * { box-sizing: border-box; }
    body { margin: 0 auto; padding: 24px 16px 8px; max-width: 760px;
      background: var(--bg); color: var(--text);
      font: 15px/1.45 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
    h1 { font-size: 20px; margin: 0 0 4px; }
    h2 { font-size: 13px; margin: 0 0 10px; color: var(--muted);
      text-transform: uppercase; letter-spacing: 0.06em; }
    .meta { color: var(--muted); margin: 0 0 8px; }
    header { margin-bottom: 16px; }
    section { background: var(--card); border: 1px solid var(--line); border-radius: 10px;
      padding: 14px 16px; margin-bottom: 12px; }
    .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr));
      gap: 12px; background: none; border: none; padding: 0; }
    .tile { background: var(--card); border: 1px solid var(--line); border-radius: 10px;
      padding: 12px 14px; }
    .tile strong { display: block; font-size: 22px; font-weight: 600; }
    .tile span { color: var(--muted); font-size: 12px; text-transform: uppercase;
      letter-spacing: 0.06em; }
    table { border-collapse: collapse; width: 100%; }
    th, td { text-align: left; padding: 5px 16px 5px 0; vertical-align: top;
      border-bottom: 1px solid var(--line); font-weight: normal; }
    tr:last-child th, tr:last-child td { border-bottom: none; }
    th { color: var(--muted); width: 200px; }
""".trimIndent()
