package com.timkrest.framehud.internal

import com.timkrest.framehud.BaselineComparison
import com.timkrest.framehud.FrameHistory
import com.timkrest.framehud.FramePhase
import com.timkrest.framehud.Incident
import com.timkrest.framehud.IncidentWindow
import com.timkrest.framehud.IntervalComparison
import com.timkrest.framehud.IntervalStats
import com.timkrest.framehud.MetricDelta
import com.timkrest.framehud.PhaseAverages
import java.util.Locale
import kotlin.math.max

internal fun SessionSnapshot.toHtml(): String = buildString {
    append("<!doctype html>\n<html lang=\"en\">\n<head>\n")
    append("<meta charset=\"utf-8\">\n")
    append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
    append("<title>FrameHUD · ").append(escapeHtml(packageName)).append("</title>\n")
    append("<style>").append(REPORT_CSS).append("</style>\n</head>\n<body>\n")
    append(reportBody())
    append("</body>\n</html>\n")
}

private fun SessionSnapshot.reportBody(): String = buildHtmlBody {
    header(title = "FrameHUD session", meta = subtitle())
    tiles {
        tile(formatCount(session.frames), "frames")
        tile(formatMs(session.p95FrameMs), "p95")
        tile(formatPercent(session.jankPercent), "jank")
        tile(formatCount(session.frozenFrames), "frozen")
    }
    confidence(this@reportBody)
    measurement(this@reportBody)
    stats(this@reportBody)
    screens(this@reportBody)
    phases(this@reportBody)
    baseline(this@reportBody)
    frameWindow(this@reportBody)
    worstFrames(this@reportBody)
    incidents(this@reportBody)
    environment(this@reportBody)
    footer("Generated by FrameHUD $frameHudVersion. Measurements never leave the device.")
}

private fun SessionSnapshot.subtitle(): String = buildString {
    append(packageName)
    appVersionName?.let { append(' ').append(it) }
    append(" (").append(appVersionCode).append(")")
    append(" · ").append(environment.label)
    append(" · ").append(formatTimestamp(takenAtEpochMs))
}

private fun HtmlScope.confidence(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement confidence") {
        val sessionIssues = session.confidence.issues
        val screenOnlyIssues = screen.confidence.issues - sessionIssues.toSet()
        if (sessionIssues.isEmpty() && screenOnlyIssues.isEmpty()) {
            meta("No issues.")
            return@section
        }
        list {
            for (issue in sessionIssues) item(issue.summary)
            for (issue in screenOnlyIssues) item("${issue.summary} — this screen only")
        }
    }
}

private fun HtmlScope.measurement(snapshot: SessionSnapshot) = with(snapshot) {
    section("Measurement") {
        table {
            row("State", measurementState())
            row("Screen", screenName ?: "—")
            row("Mark", mark ?: "—")
            if (context.isNotEmpty()) {
                chipRow("Context", context.map { (key, value) -> "$key=$value" })
            }
            row("Display", "${formatFloat(display.refreshRateHz)} Hz, budget ${formatMs(display.frameBudgetMs)}")
        }
    }
}

private fun SessionSnapshot.measurementState(): String = when {
    !isEnabled -> "disabled"
    isFrozen -> "collecting, readings frozen"
    else -> "collecting"
}

private fun HtmlScope.stats(snapshot: SessionSnapshot) = with(snapshot) {
    section("Stats") {
        table {
            headings("", "Session", "Screen")
            statRow(snapshot, "Frames") { formatCount(it.frames) }
            statRow(snapshot, "Duration") { formatSeconds(it.durationMs) }
            statRow(snapshot, "p50") { formatMs(it.p50FrameMs) }
            statRow(snapshot, "p95") { formatMs(it.p95FrameMs) }
            statRow(snapshot, "p99") { formatMs(it.p99FrameMs) }
            statRow(snapshot, "Jank") { formatPercent(it.jankPercent) }
            statRow(snapshot, "Lost time") { formatMs(it.lostTimeMs) }
            statRow(snapshot, "Frozen frames") { formatCount(it.frozenFrames) }
            statRow(snapshot, "Longest jank streak") { formatCount(it.maxJankStreak) }
            statRow(snapshot, "Dropped reports") { formatCount(it.droppedReports) }
        }
        if (session.droppedReports > 0) {
            caution("Dropped reports above zero: every other figure is undersampled.")
        }
    }
}

private fun TableScope.statRow(snapshot: SessionSnapshot, label: String, format: (IntervalStats) -> String) = with(snapshot) {
    row(label, format(session), format(screen))
}

private fun HtmlScope.screens(snapshot: SessionSnapshot) = with(snapshot) {
    val ranked = intervals.worstScreensFirst()
    if (ranked.isEmpty()) return@with
    section("Screens") {
        meta("Worst first: frozen frames, then jank, then p95. Too few frames to judge and it goes last.")
        table {
            headings("", "Frames", "Jank", "p95", "Frozen", "Budget")
            for (screen in ranked) {
                row(
                    screen.id.name,
                    formatCount(screen.stats.frames),
                    formatPercent(screen.stats.jankPercent),
                    formatMs(screen.stats.p95FrameMs),
                    formatCount(screen.stats.frozenFrames),
                    formatMs(screen.frameBudgetMs),
                )
            }
        }
    }
}

private fun HtmlScope.phases(snapshot: SessionSnapshot) = with(snapshot) {
    section("Where the time went") {
        meta("Session ${session.phases.boundBy()}, screen ${screen.phases.boundBy()}.")
        table {
            headings("", "Session", "Screen", "Peak since reset")
            phaseRow(snapshot, FramePhase.UNKNOWN_DELAY.label(), phases.unknownDelay.peak) { it.unknownDelay }
            phaseRow(snapshot, FramePhase.INPUT.label(), phases.input.peak) { it.input }
            phaseRow(snapshot, FramePhase.ANIMATION.label(), phases.animation.peak) { it.animation }
            phaseRow(snapshot, FramePhase.LAYOUT.label(), phases.layout.peak) { it.layout }
            phaseRow(snapshot, FramePhase.DRAW.label(), phases.draw.peak) { it.draw }
            phaseRow(snapshot, "UI thread", peakMs = null) { it.cpu }
            phaseRow(snapshot, FramePhase.SYNC.label(), phases.sync.peak) { it.sync }
            phaseRow(snapshot, FramePhase.COMMAND_ISSUE.label(), phases.commandIssue.peak) { it.commandIssue }
            phaseRow(snapshot, FramePhase.SWAP_BUFFERS.label(), phases.swapBuffers.peak) { it.swapBuffers }
            phaseRow(snapshot, "Render thread", peakMs = null) { it.render }
            if (session.phases.gpu != null) phaseRow(snapshot, FramePhase.GPU.label(), phases.gpu?.peak) { it.gpu }
            phaseRow(snapshot, "Unattributed", peakMs = null) { it.unattributed }
            phaseRow(snapshot, FramePhase.TOTAL.label(), phases.total.peak) { it.total }
        }
    }
}

private fun TableScope.phaseRow(
    snapshot: SessionSnapshot,
    label: String,
    peakMs: Float?,
    select: (PhaseAverages) -> Float?,
) = with(snapshot) {
    row(label, formatMs(select(session.phases)), formatMs(select(screen.phases)), formatMs(peakMs))
}

private fun HtmlScope.baseline(snapshot: SessionSnapshot) {
    val comparison = snapshot.baseline
    if (comparison is BaselineComparison.NoBaseline) return
    section("Baseline") {
        when (comparison) {
            BaselineComparison.NoBaseline -> Unit
            is BaselineComparison.OtherEnvironment -> caution(
                "Recorded on ${comparison.recorded.label}, this run is ${comparison.current.label}. " +
                    "Nothing here compares across the two.",
            )
            is BaselineComparison.Compared -> {
                if (comparison.intervals.isEmpty()) {
                    meta("Nothing this run measured has a baseline yet.")
                } else {
                    for (interval in comparison.intervals) intervalComparison(interval)
                }
            }
        }
    }
}

private fun HtmlScope.intervalComparison(comparison: IntervalComparison) {
    meta(
        "${comparison.id.label} · baseline of ${comparison.recordedRuns} run(s) · " +
            "${comparison.currentFrames} frames this run",
    )
    if (comparison.metrics.isNotEmpty()) {
        table {
            headings("", "Baseline", "Runs", "This run", "Change")
            for (delta in comparison.metrics) {
                row(
                    delta.metric.label(),
                    delta.metric.format(delta.baseline),
                    delta.baselineRuns.toString(),
                    delta.metric.format(delta.current),
                    formatChange(delta),
                )
            }
        }
    }
    if (comparison.uncompared.isNotEmpty()) {
        meta("Not compared: ${comparison.uncompared.joinToString { it.summary }}.")
    }
    val grown = comparison.grownPhases.firstOrNull() ?: return
    meta("${grown.grewTheMost()}.")
}

private fun formatChange(delta: MetricDelta): String {
    val change = delta.metric.format(delta.change).let { if (delta.change > 0f) "+$it" else it }
    val percent = delta.changePercent?.let { " ${formatChangePercent(it)}" }.orEmpty()
    return change + percent
}

private fun PhaseAverages.boundBy(): String =
    "${bottleneckStage.name.lowercase(Locale.US)} bound at ${formatMs(bottleneck)} per frame"

private fun HtmlScope.frameWindow(snapshot: SessionSnapshot) = with(snapshot) {
    section("Frame window") {
        if (window.history.size == 0) {
            meta("No frames in the window.")
            return@section
        }
        meta(
            "Last ${window.history.size} frames: p95 ${formatMs(window.p95FrameMs)} · " +
                "worst ${formatMs(window.worstFrameMs)} · red bars ran past their deadline. " +
                "${window.fps} frames in the last second.",
        )
        markup(frameChart(history = window.history, label = "Recent frame durations"))
    }
}

private fun HtmlScope.incidents(snapshot: SessionSnapshot) = with(snapshot) {
    if (incidents.isEmpty()) return@with
    section("Incidents") {
        for (incident in incidents) {
            meta(incidentHeading(incident))
            meta(incidentDetails(incident.worst))
            markup(
                frameChart(
                    history = incident.worst.frames,
                    label = "Frames around the incident",
                    framesBeforeTrigger = incident.worst.framesBeforeTrigger,
                ),
            )
        }
    }
}

private fun SessionSnapshot.incidentHeading(incident: Incident): String = buildString {
    append(incident.worst.trigger.summary)
    if (incident.occurrences == 1) {
        append(" · at ").append(formatTimeOfDay(incident.firstAtEpochMs))
        return@buildString
    }
    append(" · ").append(incident.occurrences).append(" times between ")
    append(formatTimeOfDay(incident.firstAtEpochMs)).append(" and ").append(formatTimeOfDay(incident.lastAtEpochMs))
    append(", worst at ").append(formatTimeOfDay(incident.worst.triggeredAtEpochMs))
}

private fun incidentDetails(worst: IncidentWindow): String {
    val stats = worst.stats
    return listOfNotNull(
        "${stats.frames} frames, ${worst.framesBeforeTrigger} before the trigger",
        "jank ${formatPercent(stats.jankPercent)}",
        "p95 ${formatMs(stats.p95FrameMs)}",
        "frozen ${stats.frozenFrames}".takeIf { stats.frozenFrames > 0 },
        "dropped reports ${stats.droppedReports}".takeIf { stats.droppedReports > 0 },
        "heap ${worst.memory.usedHeapMb} MB",
        worst.process.cpuPercent?.let { "cpu ${formatPercent(it)}" },
        worst.process.pssMb?.let { "pss $it MB" },
        worst.thermal.level.takeIf { it.isThrottling }?.let { "thermal ${it.name.lowercase(Locale.US)}" },
    ).joinToString(INCIDENT_DETAIL_SEPARATOR)
}

private fun frameChart(history: FrameHistory, label: String, framesBeforeTrigger: Int? = null): String {
    var scaleMs = 0f
    for (index in 0 until history.size) {
        scaleMs = max(scaleMs, max(history.totalMsAt(index), history.deadlineMsAt(index)))
    }
    if (scaleMs <= 0f) return ""
    scaleMs *= CHART_HEADROOM

    return buildString {
        append("<svg viewBox=\"0 0 $CHART_WIDTH $CHART_HEIGHT\" preserveAspectRatio=\"none\" role=\"img\" ")
        append("aria-label=\"").append(escapeHtml(label)).append("\">\n")
        val step = CHART_WIDTH / history.size
        val barWidth = step * CHART_BAR_SHARE
        for (index in 0 until history.size) {
            val totalMs = history.totalMsAt(index)
            val deadlineMs = history.deadlineMsAt(index)
            val height = CHART_HEIGHT * (totalMs / scaleMs)
            val cssClass = if (totalMs > deadlineMs) "janky" else "ok"
            append("<rect class=\"").append(cssClass).append("\" x=\"").append(formatFloat(step * index))
            append("\" y=\"").append(formatFloat(CHART_HEIGHT - height))
            append("\" width=\"").append(formatFloat(barWidth))
            append("\" height=\"").append(formatFloat(height)).append("\"/>\n")

            val deadlineY = CHART_HEIGHT * (1f - deadlineMs / scaleMs)
            append("<line class=\"deadline\" x1=\"").append(formatFloat(step * index))
            append("\" x2=\"").append(formatFloat(step * index + barWidth))
            append("\" y1=\"").append(formatFloat(deadlineY))
            append("\" y2=\"").append(formatFloat(deadlineY)).append("\"/>\n")
        }
        if (framesBeforeTrigger != null) {
            val triggerX = formatFloat(step * framesBeforeTrigger)
            append("<line class=\"trigger\" x1=\"").append(triggerX).append("\" x2=\"").append(triggerX)
            append("\" y1=\"0\" y2=\"").append(formatFloat(CHART_HEIGHT)).append("\"/>\n")
        }
        append("</svg>\n")
    }
}

private fun HtmlScope.worstFrames(snapshot: SessionSnapshot) = with(snapshot) {
    if (worstFrames.isEmpty()) return@with
    section("Worst frames") {
        table {
            headings("Time", "Duration")
            for (frame in worstFrames) {
                cells(formatTimeOfDay(frameEndEpochMs(frame.endNs)), formatMs(frame.totalMs))
            }
        }
    }
}

private fun HtmlScope.environment(snapshot: SessionSnapshot) = with(snapshot) {
    section("Environment") {
        table {
            row("Heap", "${memory.usedHeapMb} of ${memory.maxHeapMb} MB, peak ${memory.peakUsedHeapMb} MB")
            row("Native heap", "${memory.nativeHeapMb} MB, peak ${memory.peakNativeHeapMb} MB")
            row("GC since reset", "${memory.gcCount} runs, ${memory.gcTimeMs} ms")
            val headroom = thermal.headroom?.let { ", headroom ${formatFloat(it)}" }.orEmpty()
            row("Thermal", thermal.level.name.lowercase(Locale.US) + headroom)
            process.cpuPercent?.let { row("Process CPU", peaked(formatPercent(it), formatPercent(process.peakCpuPercent))) }
            process.pssMb?.let { row("PSS", peaked("$it MB", process.peakPssMb?.let { peak -> "$peak MB" })) }
            process.threads?.let { row("Threads", peaked("$it", process.peakThreads?.toString())) }
            process.openFiles?.let { row("Open files", peaked("$it", process.peakOpenFiles?.toString())) }
        }
        if (thermal.level.isThrottling) {
            caution("Thermal throttling: timings are not comparable to a cold run.")
        }
    }
}

private const val INCIDENT_DETAIL_SEPARATOR = " · "

private fun peaked(value: String, peak: String?): String = if (peak == null) value else "$value, peak $peak"

private fun formatMs(value: Float?): String = if (value == null) "—" else "${formatFloat(value)} ms"

private fun formatMs(value: Int?): String = if (value == null) "—" else "$value ms"

private fun formatPercent(value: Float?): String = if (value == null) "—" else "${formatFloat(value)}%"

private fun formatSeconds(durationMs: Long): String = String.format(Locale.US, "%.1f s", durationMs / MS_PER_SECOND_D)

private fun formatCount(value: Int): String = value.toString()

private fun formatFloat(value: Float): String = String.format(Locale.US, "%.1f", value)

private const val MS_PER_SECOND_D = 1000.0
private const val CHART_WIDTH = 600f
private const val CHART_HEIGHT = 120f
private const val CHART_BAR_SHARE = 0.8f
private const val CHART_HEADROOM = 1.05f

private val REPORT_CSS = """
    :root { color-scheme: light dark;
      --bg: #f7f7f5; --card: #ffffff; --text: #1c1c1a; --muted: #6d6d68; --line: #e4e4df;
      --ok: #4c9a52; --janky: #c94f42; --deadline: #1c1c1a; --caution: #9a6b00; }
    @media (prefers-color-scheme: dark) { :root {
      --bg: #191918; --card: #212120; --text: #ececea; --muted: #9c9c96; --line: #33332f;
      --ok: #5aa860; --janky: #d8695c; --deadline: #ececea; --caution: #d0a13e; } }
    * { box-sizing: border-box; }
    body { margin: 0 auto; padding: 24px 16px 8px; max-width: 760px;
      background: var(--bg); color: var(--text);
      font: 15px/1.45 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
    h1 { font-size: 20px; margin: 0 0 4px; }
    h2 { font-size: 13px; margin: 0 0 10px; color: var(--muted);
      text-transform: uppercase; letter-spacing: 0.06em; }
    .meta { color: var(--muted); margin: 0 0 8px; }
    header { margin-bottom: 16px; }
    section { background: var(--card); border: 1px solid var(--line); border-radius: 10px;
      padding: 14px 16px; margin-bottom: 12px; }
    .tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(110px, 1fr));
      gap: 12px; background: none; border: none; padding: 0; }
    .tile { background: var(--card); border: 1px solid var(--line); border-radius: 10px;
      padding: 12px 14px; }
    .tile strong { display: block; font-size: 22px; font-weight: 600; }
    .tile span { color: var(--muted); font-size: 12px; text-transform: uppercase;
      letter-spacing: 0.06em; }
    table { border-collapse: collapse; width: 100%; }
    th, td { text-align: left; padding: 5px 16px 5px 0; vertical-align: top;
      border-bottom: 1px solid var(--line); font-weight: normal; }
    tr:last-child th, tr:last-child td { border-bottom: none; }
    th { color: var(--muted); width: 200px; }
    tr > th:not(:first-child) { width: auto; }
    code { background: var(--bg); border: 1px solid var(--line); border-radius: 5px;
      padding: 1px 6px; font-size: 13px; }
    svg { display: block; width: 100%; height: 120px; margin-top: 8px; }
    svg .ok { fill: var(--ok); }
    svg .janky { fill: var(--janky); }
    svg .deadline { stroke: var(--deadline); stroke-width: 1; opacity: 0.55; }
    svg .trigger { stroke: var(--caution); stroke-width: 2; }
    .caution { color: var(--caution); margin: 10px 0 0; }
    footer { color: var(--muted); font-size: 12px; padding: 8px 0 24px; }
""".trimIndent()
