package com.timkrest.framehud.ui

internal const val LABEL_HEADER_FROZEN = "FROZEN"
internal const val LABEL_EMULATOR = "EMU"
internal const val LABEL_CPU_SECTION = "CPU"
internal const val LABEL_RENDER_SECTION = "RENDER"
internal const val LABEL_GPU_SECTION = "GPU"

internal const val LABEL_HOST_SECTION = " · host"
internal const val LABEL_INPUT = "input"
internal const val LABEL_ANIMATION = "anim"
internal const val LABEL_LAYOUT = "layout"
internal const val LABEL_DRAW = "draw"
internal const val LABEL_SYNC = "sync"
internal const val LABEL_COMMAND = "command"
internal const val LABEL_SWAP = "swap"
internal const val LABEL_GPU = "gpu"
internal const val LABEL_DELAY = "delay"
internal const val LABEL_OTHER = "other"
internal const val LABEL_TOTAL = "TOTAL"
internal const val LABEL_OVERRUN = "over"
internal const val LABEL_PIPE_CPU = "pipe:cpu"
internal const val LABEL_PIPE_RENDER = "pipe:rt"
internal const val LABEL_PIPE_GPU = "pipe:gpu"
internal const val LABEL_IDLE = "idle"
internal const val LABEL_GPU_NA = "n/a"
internal const val LABEL_VERDICT_OK = "✓ ok"
internal const val LABEL_COLUMN_NOW = "now"
internal const val LABEL_COLUMN_AVG = "avg"
internal const val LABEL_COLUMN_PEAK = "peak"

internal const val MARK_PREFIX = "▸ "
internal const val ELLIPSIS = "…"

internal const val ATTENTION_MARKER = " ◀"
internal const val COLLAPSED_SEPARATOR = "  "

internal const val ICON_DETACH = "⧉"
internal const val ICON_COLLAPSE = "▾"
internal const val ICON_RESET = "×"
